# Changes here will be overwritten by Copier
_commit: 9c45cb7
_src_path: git@github.com:inokufu/python-project-template.git
author_email: contact@inokufu.com
author_name: Inokufu
min_python_version: '3.13'
package_name: logger
project_description: Python logger
project_name: Logger
